import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { config } from "../wagmi";
import { getAccount, writeContract } from "@wagmi/core";
import Director from "../../abi/Director.json";
import { parseEther } from "viem";

const dapp: NextPage = () => {
  const [cexValue, setCexValue] = React.useState("0");
  const [BTC_USD, setBTC_USD] = React.useState(0.0);

  const invest = async () => {
    const investAmount = (
      document.getElementById("investAmount") as HTMLInputElement
    ).value;
    console.log(cexValue);
    getConvertionRate_currency_BTC().then(() => {
      console.log(BTC_USD);
      console.log(parseFloat(investAmount) / BTC_USD);
      writeContract(config, {
        abi: Director.abi,
        address: "0x725E60Adb60332D8C47d9FDA860ff34dD57ABA25",
        functionName: "addLiquidity",
        args: [cexValue],
        value: parseEther((parseFloat(investAmount) / BTC_USD).toString()),
      });
    });
  };

  const getConvertionRate_currency_BTC = async () => {
    var convertionRate_currency_ETH = 0.0;
    try {
      const response = await fetch(
        `https://api.coinbase.com/v2/exchange-rates?currency=BTC`
      );
      const data = await response.json();
      convertionRate_currency_ETH = data.data.rates.USD;
      console.log(convertionRate_currency_ETH);

      setBTC_USD(convertionRate_currency_ETH);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header
        style={{
          //centrar
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          padding: "10px",
        }}
      >
        {<ConnectButton />}
      </header>

      <main className={styles.main}>
        <div
          style={{
            flexDirection: "column",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: "white",
            width: "500px",
            height: "400px",
            borderRadius: "10px",
            padding: "30px",
          }}
        >
          <h1 style={{ fontSize: "20px", margin: "10px" }}>
            How much do you want to invest? (in USD)
          </h1>
          <input
            style={{
              width: "100%",
              height: "50px",
              borderRadius: "5px",
              padding: "10px",
              margin: "10px",
              fontSize: "30px",
            }}
            placeholder="10"
            id="investAmount"
          />
          <h1 style={{ fontSize: "20px", margin: "10px" }}>
            Where do you want to invest?
          </h1>
          <select
            style={{
              width: "100%",
              height: "50px",
              borderRadius: "5px",
              padding: "10px",
              margin: "10px",
              fontSize: "25px",
              backgroundColor: "white",
            }}
            value={cexValue}
            onChange={(e) => setCexValue(e.target.value)}
          >
            <option value="0">Binance</option>
            <option value="1">Kucoin</option>
            <option value="2">Kraken</option>
            <option value="3">Coinbase</option>
          </select>
          <button
            style={{
              border: "none",
              cursor: "pointer",
              background: "#11b4d8",
              color: "white",
              borderRadius: "10px",
              height: "50px",
              width: "200px",
              fontSize: "20px",
              padding: "10px",
              margin: "10px",
            }}
            onClick={invest}
          >
            Invest
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default dapp;
